apiVersion: v1
kind: Pod 
metadata:
  name: pod-tomcat
  labels:
    name: pod-webapp-lable
spec:
  containers:
    - name: pod-tomcat-container
      image: tomcat
      imagePullPolicy: Never
      env:
      - name: ENV_TEST_1
        value: env_test_1
      - name: ENV_TEST_2
        value: env_test_2
      ports:
      - containerPort: 8080
       # hostPort: 8089 失效
