apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecdataapi
  namespace: kube-system

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ecdataapi
subjects:
  - kind: ServiceAccount
    name: ecdataapi
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
