apiVersion: v1
kind: ReplicationController
metadata:
   name: rc-nginx
   labels: 
     name: rc-nginx-label
spec:
  replicas: 2
  template: 
    metadata:
     labels:
       name: rc-nginx-template-label
    spec:
      containers:
      - name: rc-nginx-container-1
        image: lijincheng1/nginx:v8
        ports:
        - containerPort: 80