apiVersion: v1
kind: Service
metadata:
  name: svc-1-name
  labels:
    name: svc-1-label
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8080  # container的端口
    nodePort: 30001
    name: web

  - port: 8085
    targetPort: 8080
    name: management 
  
  selector:
    name: rc-tomcat-template-label
