kind: ConfigMap
apiVersion: v1
metadata:
  name: cf-appvars
  namespace: default  
  labels:
    software: apache
    project: lykops
    app: configmap
    version: v1
data:
  apploglevel: info
  appVersion: v1.0
  os: linux
